spring: # 주의할 점은 내용작성시 들여쓰기 내어쓰기를 반드시 꼭 지켜야 한다.
  application:
    name: FinalProject

  profiles: # 실행환경(local(로컬),dev(개발),real(운영))
    active: local

  mvc:
    view: # 뷰 리졸버. JSP를 뷰로 사용
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource: # DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@211.63.89.70:1521:xe     # SID 방식
    username: FINAL_ORAUSER4
    password: seven
    type: com.zaxxer.hikari.HikariDataSource
    hikari: # 커넥션풀
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  data: #=== (몽고DB) === 
    mongodb:
      uri: mongodb://devuser:qwer1234$@127.0.0.1:27017/mydb

  messages: # 메시지
    basename: messages.validation
    encoding: UTF-8

  devtools: # View reload
    livereload:
      enabled: true
    restart:
      enabled: true

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
      - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration

  jackson:
    time-zone: Asia/Seoul
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false  # ISO-8601 문자열로 응답 (날짜/시간)

logging: # 로그 지정
  level:
    '[com.spring.app]': debug
    # 날씨 패키지 로깅을 추가해 외부 호출/파싱 문제를 바로 확인
    'com.spring.app.weather': debug

mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: com.spring.app.**.domain

server:
  port: 9090
  servlet:
    context-path: /finalproject
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  tomcat:
    max-part-count: -1

# === 기상청 공공데이터 API 설정 ===
kma:
  # 기상청 단기/초단기 서비스 공통 base-url
  base-url: https://apis.data.go.kr/1360000
  # service-key는 보안상 환경변수로 주입 권장.
  # - 이미 URL-인코딩된 값을 쓰고 있다면 아래처럼 그대로 넣어도 됩니다.
  # - 환경변수 사용 시: KMA_SERVICE_KEY_ENC 에 "인코딩된" 키를 넣으세요.
  service-key: ${KMA_SERVICE_KEY_ENC:ijKxiVrmE9lJ104b7yfrf9PyP%2FV5OyjKxXYhc%2F%2FYzy72jQz7cPlt%2FEjD%2B%2Bc%2Bneb4%2BxnneBu6UR6h6L95X8KbGQ%3D%3D}

  # 선택: 기본 좌표/지점 (컨트롤러 기본값에 사용 가능)
  default:
    # 한독빌딩 근처 위/경도 (원하면 바꾸세요)
    lat: 37.499447
    lon: 127.033263
    # 격자 좌표(nx, ny) – 좌표 변환이 실패할 때 폴백용
    nx: 60
    ny: 127